site_name: Les secrets des réseaux
site_url: https://ccouturi.gitlabpages.inria.fr/mpls-reseaux/
site_dir: public
site_author: Anne-Hélène Tual, Anthony Penhard, Christophe Couturier

nav:
- Accueil: 'index.md'
- Activités:
  - Configuration de ma machine: 'activite-config-machine.md'
  - Mesures de délais: 'activite-mesure-delais.md'
- Glossaire: 'glossaire.md'
- Ressources: 'ressources.md'
- MPLS: 'https://www.maisons-pour-la-science.org/fr/bretagne'


theme:
  # name: mkdocs
  # name: readthedocs
  # name: cinder
  # name: flatly # pip3 install mkdocs-bootswatch 
  name: superhero # pip3 install mkdocs-bootswatch 
  # darkly, litera, lumen, lux, materia, minty, pulse, sandstone, solar, and superhero
  custom_dir: theme_custom/

  # name: material
  # palette:
  #   # Light mode
  #   - scheme: default
  #     primary: indigo
  #     accent: indigo
  #     toggle:
  #       icon: material/toggle-switch-off-outline
  #       name: Switch to dark mode

  #   # Dark mode
  #   - scheme: slate
  #     primary: blue
  #     accent: blue
  #     toggle:
  #       icon: material/toggle-switch
  #       name: Switch to light mode

plugins:
  # - search
  - search:
      lang: fr
  - markdownextradata

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.details
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  # - markdown.extensions.fenced_code
  # - codehilite:
  #     guess_lang: false
      # linenums: true
  - pymdownx.arithmatex #  pip3 install pymdown-extensions; cf. https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
  # - pymdownx.betterem:
  #     smart_enable: all
  # - pymdownx.caret
  # - pymdownx.critic
  # - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - pymdownx.inlinehilite
  # - pymdownx.magiclink
  # - pymdownx.mark
  # - pymdownx.smartsymbols
  # - pymdownx.superfences
  # - pymdownx.tasklist:
  #     custom_checkbox: true
  # - pymdownx.tilde
  - abbr # for abbreviations
  - pymdownx.snippets # for abbreviations central include
  - toc:
      # baselevel: 1
      permalink: False

extra_css:
    - css/extra.css

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'



