site_name: Les secrets des réseaux
site_url: https://ccouturi.gitlabpages.inria.fr/mpls-reseaux/
site_dir: public
site_author: Anne-Hélène Tual, Anthony Penhard, Christophe Couturier
#copyright: Copyright &copy; 2021, A.H. Tual, A. Penhard, C. Couturier. Contenu sous licence  <a href="http://creativecommons.org/licenses/by/4.0/deed.fr">CC BY &nbsp;  <a rel="license" href="http://creativecommons.org/licenses/by/4.0/deed.fr"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a>
copyright: Copyright &copy; 2021-2022, A.H. Tual, A. Penhard, C. Couturier. Contenu sous licence  <a href="http://creativecommons.org/licenses/by/4.0/deed.fr">CC BY &nbsp; <a rel="license" href="http://creativecommons.org/licenses/by/4.0/deed.fr" target="_blank"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png"/></a></br>Code source disponible sur <a href="https://github.com/whaou/mpls-reseaux/"target="_blank">ce dépôt Github</a>.

nav:
  - Accueil: "index.md"
  - Activités:
      # - Liens pour les réponses aux activités: "activite-les-reseaux-c_est.md"
      # - Installation des logiciels: "installations.md"
      - Simulation réseau avec Filius: "activite-filius.md"
      - Internet des objets avec micro:bit: "activite-IoT-micro-bit.md"
      # - L'environnement de TP à IMT Atlantique: "activite-environnement-imta.md"
  - Archives  session 2021:
      - Configuration de ma machine: "activite-config-machine.md"
      - Mesures de délais: "activite-mesure-delais.md"
  # TODO: activate glossary bellow after the first activity
  - Glossaire: "glossaire.md"
  - Ressources: "ressources.md"
  - MPLS: "https://www.maisons-pour-la-science.org/fr/bretagne"

theme:
  favicon: img/favicon.ico
  # name: mkdocs
  # name: readthedocs
  # name: cinder
  # name: flatly # pip3 install mkdocs-bootswatch
  # darkly, litera, lumen, lux, materia, minty, pulse, sandstone, solar, and superhero
  name: superhero # pip3 install mkdocs-bootswatch
  custom_dir: theme_custom/

  # name: material
  # language: fr
  # palette:
  #   scheme: slate
  #   primary: blue grey
  # features:
  #   - navigation.instant

plugins:
  - search:
      lang: fr
  - markdownextradata

markdown_extensions:
  - codehilite
  - admonition
  - abbr # for abbreviations
  - pymdownx.snippets # for abbreviations central include
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - attr_list
  - def_list
  - pymdownx.arithmatex #  pip3 install pymdown-extensions; cf. https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
  # - pymdownx.caret
  # - pymdownx.mark
  # - pymdownx.tilde
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      # baselevel: 1
      permalink: False
  - attr_list

extra_css:
  - css/extra.css
  - css/tabbed.css
  # - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css

extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML"
  # - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
  # - javascripts/config.js
